'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),errors=[],out=process.env.TEST_OUTPUT||'/tmp/daqin-v4-check';fs.mkdirSync(out,{recursive:true});
try{
  const context=await browser.newContext({viewport:{width:1280,height:720}}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());const requests=[];p.on('request',r=>requests.push(r.url()));
  await p.goto('file://'+path.resolve(__dirname,'../index.html'));await p.locator('#new').click();await p.locator('#pause').click();await p.locator('[data-city="0"]').click();await p.locator('[data-build="homes"]').click();assert.match(await p.locator('#resources').textContent(),/\+8\/秒/);assert.equal(await p.locator('[data-city="9"]').count(),0);
  await p.locator('[data-recruit="0"]').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('daqin-save-v4')).cities[0].troops[0]),85);
  await p.locator('#save').click();await p.locator('#slot-name').fill('浏览器测试');await p.locator('#save-current').click();assert.equal(await p.locator('[data-load]').count(),2);await p.locator('#close-saves').click();await p.locator('#close-details').click();
  const m=await p.locator('#map').boundingBox(),scale=Math.min(m.width/1536,m.height/499,1),offset={x:m.x+(m.width-1536*scale)/2,y:m.y+(m.height-499*scale)/2};const cp=(x,y)=>({x:offset.x+x*1536*scale,y:offset.y+y*499*scale});const c2=cp(.441,.275);await p.mouse.click(c2.x,c2.y,{button:'right'});await p.locator('#all-troops').click();await p.locator('#confirm-order').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('daqin-save-v4')).armies.length),1);
  await p.screenshot({path:path.join(out,'1280-world.png')});await p.mouse.dblclick(c2.x,c2.y);assert.equal(await p.locator('#world-view').isVisible(),true);await p.screenshot({path:path.join(out,'1280-city-dark.png')});await p.locator('#world-view').click();
  await p.locator('[data-city="0"]').click();await p.locator('#enter-city').click();await p.screenshot({path:path.join(out,'1280-city.png')});await p.setViewportSize({width:1920,height:1080});await p.screenshot({path:path.join(out,'1920-city.png')});
  await p.locator('#world-view').click();await p.mouse.move(900,400);await p.mouse.wheel(0,-400);await p.mouse.down({button:'middle'});await p.mouse.move(1000,450);await p.mouse.up({button:'middle'});await p.screenshot({path:path.join(out,'1920-world-zoom.png')});
  await p.reload();await p.locator('#continue').click();assert.equal(await p.evaluate(()=>DaqinDiagnostics.visible().paused),true);assert.equal(await p.evaluate(()=>localStorage.getItem('daqin-save-v4')!==null),true);assert.ok(requests.every(u=>!/^https?:/.test(u)));console.log('single-player file://, economy, recruitment, dispatch, save/reload, layer switching, two layouts: passed');
  const clients=[];for(let i=0;i<3;i++){const c=await browser.newContext({viewport:{width:1280,height:720}}),page=await c.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.TEST_URL||'http://127.0.0.1:8188');await page.locator('#network').click();await page.locator('#create-room').waitFor({state:'visible'});clients.push(page);}
  const [a,b,c]=clients;await a.locator('#create-room').click();await a.locator('#room-info h3').waitFor();const code=(await a.locator('#room-info h3').textContent()).match(/[A-F0-9]{6}/)[0];for(const page of [b,c]){await page.locator('#room-code').fill(code);await page.locator('#join-room').click();await page.locator('#ready').waitFor({state:'visible'});}for(const page of clients)await page.locator('#ready').click();await a.locator('#start-room').click();for(const page of clients)await page.waitForFunction(()=>DaqinDiagnostics.visible()?.mode==='multi');
  const views=await Promise.all(clients.map(p=>p.evaluate(()=>DaqinDiagnostics.visible())));assert.deepEqual(views.map(v=>v.player),[0,1,2]);assert.ok(views[0].cities[9].hidden);assert.ok(views[2].cities[0].hidden);await a.locator('#pause').click();await b.locator('#pause').click();await c.locator('#pause').click();await a.waitForFunction(()=>DaqinDiagnostics.visible().paused);await a.screenshot({path:path.join(out,'three-player-paused.png')});await b.locator('#pause').click();await a.waitForFunction(()=>!DaqinDiagnostics.visible().paused);
  await b.reload();await b.locator('#network').click();await b.locator('#join-room').click();await b.waitForFunction(()=>DaqinDiagnostics.visible()?.player===1);console.log('three independent browser sessions: factions, filtered states, unanimous pause/resume, refresh reconnect: passed');
  assert.deepEqual(errors,[]);console.log('page errors: 0; single-player external requests: 0');console.log('screenshots: '+out);console.log('render performance: '+JSON.stringify(await p.evaluate(()=>DaqinDiagnostics.performance())));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
