'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const overlap=(a,b)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),out=process.env.TEST_OUTPUT||'/tmp/daqin-world-ui';fs.mkdirSync(out,{recursive:true});
  try{const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());const url='file://'+path.resolve(__dirname,'../index.html');
    await p.goto(url);await p.locator('#new').click();await p.locator('#pause').click();
    const cityPoint=async id=>{const map=await p.locator('#map').boundingBox(),v=await p.evaluate(id=>{const t=DaqinDiagnostics.layout().transform,[x,y]=DaqinAssets.positions[id];return {x:t.x+x*t.w,y:t.y+y*t.h};},id);return {x:map.x+v.x,y:map.y+v.y};};
    for(const [width,height]of [[1280,720],[1920,1080]]){await p.setViewportSize({width,height});await p.waitForTimeout(50);const side=await p.locator('#details').boundingBox(),map=await p.locator('#map').boundingBox();assert.ok(side&&map&&!overlap(side,map));assert.equal(await p.locator('.city-summary').count(),2);assert.equal(await p.locator('#orders input').count(),0);await p.screenshot({path:path.join(out,`${width}-overview.png`)});}
    const neutral=await cityPoint(2);await p.mouse.click(neutral.x,neutral.y,{button:'right'});assert.equal(await p.locator('#dispatch').evaluate(d=>d.open),false);
    const own=await cityPoint(0);await p.mouse.click(own.x,own.y,{button:'right'});await p.locator('#dispatch[open]').waitFor();assert.equal(await p.locator('#dispatch-target option').count(),3);assert.deepEqual(await p.locator('[data-dispatch-troop]').evaluateAll(xs=>xs.map(x=>Number(x.value))),[32,17,20]);await p.screenshot({path:path.join(out,'dispatch-dialog.png')});
    await p.locator('#all-troops').click();assert.deepEqual(await p.locator('[data-dispatch-troop]').evaluateAll(xs=>xs.map(x=>Number(x.value))),[65,35,40]);await p.locator('#dispatch-target').selectOption('2');await p.locator('#confirm-order').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('daqin-save-v4')).armies.length),1);
    const reset=async kind=>{await p.goto('about:blank');await p.goto(url);await p.locator('#start[open]').waitFor();await p.evaluate(kind=>{const s=Daqin.create();if(kind==='single'){s.factions[0].gold=32;s.factions[0].food=24;}else{s.cities[2].owner=0;s.cities[2].troops=[0,0,0];s.cities[0].recruitAt=10;s.factions[0].gold=64;s.factions[0].food=48;}localStorage.setItem('daqin-save-v4',Daqin.serialize(s));},kind);await p.locator('#continue').click();};
    await reset('single');await p.locator('[data-city-recruit="0"][data-troop="0"]').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('daqin-save-v4')).cities[0].troops[0]),85);assert.equal(await p.locator('[data-city-recruit="1"][data-troop="0"]').isDisabled(),true);
    await reset('bulk');await p.locator('#bulk-troop').selectOption('2');await p.locator('#bulk-recruit').click();const state=await p.evaluate(()=>JSON.parse(localStorage.getItem('daqin-save-v4')));assert.deepEqual(state.cities.slice(0,3).map(c=>c.troops),[[65,35,40],[65,35,60],[0,0,20]]);assert.equal(state.factions[0].gold,0);
    await p.locator('[data-overview-city="1"]').click();assert.equal(await p.locator('.city-summary.active strong').textContent(),'巴蜀');assert.equal(await p.locator('.city-expanded').count(),1);assert.deepEqual(errors,[]);console.log('world overview, individual/bulk recruitment, own-city dispatch dialog and layouts: passed');console.log('screenshots: '+out);
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
