'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox']});try{const p=await b.newPage({viewport:{width:1280,height:720}});p.on('dialog',d=>d.accept());const url='file://'+path.resolve(__dirname,'../index.html');await p.route('**/world-map.png',r=>r.abort());await p.goto(url);await p.locator('#retry').waitFor({state:'visible'});assert.match(await p.locator('#load-text').textContent(),/world-map.png/);assert.equal(await p.locator('#loading').evaluate(d=>d.open),true);await p.unroute('**/world-map.png');await p.locator('#retry').click();await p.locator('#new').click();await p.locator('#pause').click();
  await p.locator('#save').click();await p.locator('#slot-name').fill('甲');await p.locator('#save-current').click();await p.locator('[data-overwrite]').click();await p.locator('[data-delete]').last().click();assert.equal(await p.locator('[data-overwrite]').count(),0);await p.locator('#close-saves').click();
  const box=await p.locator('#map').boundingBox(),base=Math.min(box.width/1536,box.height/499,1),origin={x:box.x+(box.width-1536*base)/2,y:box.y+(box.height-499*base)/2},anchor={x:box.x+box.width/2,y:box.y+box.height/2};await p.mouse.move(anchor.x,anchor.y);await p.mouse.wheel(0,-300);await p.waitForTimeout(100);await p.mouse.down({button:'middle'});await p.mouse.move(anchor.x+80,anchor.y+25);await p.mouse.up({button:'middle'});const z=Math.exp(.3),x=anchor.x+(origin.x+.45*1536*base-anchor.x)*z+80,y=anchor.y+(origin.y+.411*499*base-anchor.y)*z+25;await p.mouse.click(x,y);assert.match(await p.locator('#city-panel').textContent(),/咸阳/);await p.locator('#close-details').click();await p.mouse.dblclick(x,y);assert.match(await p.locator('#view-title').textContent(),/咸阳/);
  const resultRaw=await p.evaluate(()=>{const s=Daqin.create();s.recordId='result-dedup-test';s.cities.forEach(c=>{c.owner=0;c.guard=null;});s.heroes.filter(h=>h.owner!==0).forEach(h=>h.city=null);Daqin.eliminate(s);return Daqin.serialize(s);});
  await p.goto('about:blank');await p.goto(url);await p.locator('#start[open]').waitFor();await p.evaluate(raw=>localStorage.setItem('daqin-save-v4',raw),resultRaw);await p.locator('#continue').click();await p.locator('#result-title').waitFor({state:'visible'});await p.reload();await p.locator('#continue').click();assert.equal(await p.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('daqin-results-v4'))).filter(k=>k==='result-dedup-test:0').length),1);
  console.log('missing map blocks play and retries; save overwrite/delete; zoom/pan click and double-click; result dedup after reload: passed');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
